allowLineBreaksInTitles: true
color: null
description: "The individual images in a column on the Home Page.\r\nYou can control wether the image should be a still(single image), or image show (several images showing after each other), and mp4, or gif.\r\nIf you choose \"Image Show\" you will also upload just single images, and you will be able to control the speed of the image play."
fieldLayouts:
  9ae9de9d-c8dd-4878-97f0-643cb629779c:
    cardThumbAlignment: end
    tabs:
      -
        elementCondition: null
        elements:
          -
            dateAdded: '2026-05-11T14:03:44+00:00'
            editCondition: null
            elementCondition: null
            elementEditCondition: null
            fieldUid: 41b9d6e7-c976-48b4-95d3-01c0f53f059e # Media Type
            handle: null
            instructions: null
            label: null
            required: true
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: c3510a01-edad-4689-bf18-6494f50f0513
            userCondition: null
            warning: null
            width: 100
          -
            autocapitalize: true
            autocomplete: false
            autocorrect: true
            class: null
            dateAdded: '2026-05-11T10:16:01+00:00'
            disabled: false
            elementCondition: null
            id: null
            inputType: null
            instructions: null
            label: null
            max: null
            min: null
            name: null
            orientation: null
            placeholder: null
            readonly: false
            required: true
            size: null
            step: null
            tip: null
            title: null
            type: craft\fieldlayoutelements\entries\EntryTitleField
            uid: efea1286-7059-47e5-95b0-6ad1ab887cc7
            userCondition: null
            warning: null
            width: 100
          -
            dateAdded: '2026-05-11T15:25:00+00:00'
            editCondition: null
            elementCondition: null
            elementEditCondition: null
            fieldUid: 029a29ca-e3b5-477b-a282-8ee3635d8744 # Linked Project
            handle: null
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: 2eb7e882-2cda-4ed7-91ce-ae59026370eb
            userCondition: null
            warning: null
            width: 100
          -
            dateAdded: '2026-05-11T10:34:25+00:00'
            editCondition: null
            elementCondition: null
            elementEditCondition: null
            fieldUid: 0776be5d-4a08-4d09-8fa6-976025b42e0f # Client
            handle: null
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: f2acc8f9-127f-465e-b771-e7381f3ff21e
            userCondition: null
            warning: null
            width: 100
          -
            dateAdded: '2026-05-11T10:34:25+00:00'
            editCondition: null
            elementCondition: null
            elementEditCondition: null
            fieldUid: a4767100-10cc-4b48-87bd-2246e9965fd8 # Project Type
            handle: null
            instructions: null
            label: null
            required: true
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: 334f8e22-8781-40ad-a226-3791e23f1494
            userCondition: null
            warning: null
            width: 100
          -
            dateAdded: '2026-05-11T14:03:44+00:00'
            editCondition: null
            elementCondition:
              class: craft\elements\conditions\entries\EntryCondition
              conditionRules:
                -
                  class: craft\fields\conditions\OptionsFieldConditionRule
                  fieldUid: 41b9d6e7-c976-48b4-95d3-01c0f53f059e # Media Type
                  layoutElementUid: c3510a01-edad-4689-bf18-6494f50f0513
                  operator: in
                  uid: 56546fc2-3461-4bb9-87b5-0ad09e7325e9
                  values:
                    - singleImage
              elementType: craft\elements\Entry
              fieldContext: global
            elementEditCondition:
              class: craft\elements\conditions\entries\EntryCondition
              conditionRules:
                -
                  class: craft\fields\conditions\OptionsFieldConditionRule
                  fieldUid: 41b9d6e7-c976-48b4-95d3-01c0f53f059e # Media Type
                  layoutElementUid: c3510a01-edad-4689-bf18-6494f50f0513
                  operator: in
                  uid: e223ef2e-f7b6-44db-850a-30bd355134b5
                  values:
                    - singleImage
              elementType: craft\elements\Entry
              fieldContext: global
            fieldUid: bce2d6b0-da34-407d-ba88-c57f37f812e3 # Single Image
            handle: null
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: 82725ae0-9bea-47ca-9e1d-210b7136eb1d
            userCondition: null
            warning: null
            width: 50
          -
            dateAdded: '2026-05-11T14:03:44+00:00'
            editCondition: null
            elementCondition:
              class: craft\elements\conditions\entries\EntryCondition
              conditionRules:
                -
                  class: craft\fields\conditions\OptionsFieldConditionRule
                  fieldUid: 41b9d6e7-c976-48b4-95d3-01c0f53f059e # Media Type
                  layoutElementUid: c3510a01-edad-4689-bf18-6494f50f0513
                  operator: in
                  uid: 0814f339-cfb8-4dea-a63b-ebdafc771c40
                  values:
                    - multiImage
              elementType: craft\elements\Entry
              fieldContext: global
            elementEditCondition:
              class: craft\elements\conditions\entries\EntryCondition
              conditionRules:
                -
                  class: craft\fields\conditions\OptionsFieldConditionRule
                  fieldUid: 41b9d6e7-c976-48b4-95d3-01c0f53f059e # Media Type
                  layoutElementUid: c3510a01-edad-4689-bf18-6494f50f0513
                  operator: in
                  uid: bf04622d-21ff-45e5-9faa-72e7723a8a26
                  values:
                    - multiImage
              elementType: craft\elements\Entry
              fieldContext: global
            fieldUid: 9b541b36-da6b-431d-8255-f58bc7375a5c # Multi Image
            handle: null
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: 65a19b98-0c77-44db-bf1f-420a695ffb07
            userCondition: null
            warning: null
            width: 50
          -
            dateAdded: '2026-05-11T14:09:04+00:00'
            editCondition: null
            elementCondition:
              class: craft\elements\conditions\entries\EntryCondition
              conditionRules:
                -
                  class: craft\fields\conditions\OptionsFieldConditionRule
                  fieldUid: 41b9d6e7-c976-48b4-95d3-01c0f53f059e # Media Type
                  layoutElementUid: c3510a01-edad-4689-bf18-6494f50f0513
                  operator: in
                  uid: b6cd7168-8d15-410a-8957-d7956c2cc20a
                  values:
                    - multiImage
              elementType: craft\elements\Entry
              fieldContext: global
            elementEditCondition:
              class: craft\elements\conditions\entries\EntryCondition
              conditionRules:
                -
                  class: craft\fields\conditions\OptionsFieldConditionRule
                  fieldUid: 41b9d6e7-c976-48b4-95d3-01c0f53f059e # Media Type
                  layoutElementUid: c3510a01-edad-4689-bf18-6494f50f0513
                  operator: in
                  uid: 105f6ccb-9272-4ae3-9f44-933543563546
                  values:
                    - multiImage
              elementType: craft\elements\Entry
              fieldContext: global
            fieldUid: f4438e25-a02a-4b6e-a38a-142915a42244 # multiImageSpeed
            handle: null
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: 16ad6eea-5736-4816-8e7e-d1f03ae0e00b
            userCondition: null
            warning: null
            width: 25
          -
            dateAdded: '2026-05-11T14:03:44+00:00'
            editCondition: null
            elementCondition:
              class: craft\elements\conditions\entries\EntryCondition
              conditionRules:
                -
                  class: craft\fields\conditions\OptionsFieldConditionRule
                  fieldUid: 41b9d6e7-c976-48b4-95d3-01c0f53f059e # Media Type
                  layoutElementUid: c3510a01-edad-4689-bf18-6494f50f0513
                  operator: in
                  uid: 57876731-605b-4abc-8b41-52a65cfc8db1
                  values:
                    - video
              elementType: craft\elements\Entry
              fieldContext: global
            elementEditCondition:
              class: craft\elements\conditions\entries\EntryCondition
              conditionRules:
                -
                  class: craft\fields\conditions\OptionsFieldConditionRule
                  fieldUid: 41b9d6e7-c976-48b4-95d3-01c0f53f059e # Media Type
                  layoutElementUid: c3510a01-edad-4689-bf18-6494f50f0513
                  operator: in
                  uid: bb007b43-d243-4e12-9f64-c63ac2ae5f70
                  values:
                    - video
              elementType: craft\elements\Entry
              fieldContext: global
            fieldUid: 75af86be-349d-4dec-ac9e-431ffbe54ebc # Video
            handle: null
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: 46e7e709-2a0b-4a9d-bb5b-7c1f0387cb2d
            userCondition: null
            warning: null
            width: 50
          -
            dateAdded: '2026-05-11T14:09:04+00:00'
            editCondition: null
            elementCondition:
              class: craft\elements\conditions\entries\EntryCondition
              conditionRules:
                -
                  class: craft\fields\conditions\OptionsFieldConditionRule
                  fieldUid: 41b9d6e7-c976-48b4-95d3-01c0f53f059e # Media Type
                  layoutElementUid: c3510a01-edad-4689-bf18-6494f50f0513
                  operator: in
                  uid: 549e078e-f759-4022-9ed2-4b14e6554773
                  values:
                    - gif
              elementType: craft\elements\Entry
              fieldContext: global
            elementEditCondition:
              class: craft\elements\conditions\entries\EntryCondition
              conditionRules:
                -
                  class: craft\fields\conditions\OptionsFieldConditionRule
                  fieldUid: 41b9d6e7-c976-48b4-95d3-01c0f53f059e # Media Type
                  layoutElementUid: c3510a01-edad-4689-bf18-6494f50f0513
                  operator: in
                  uid: d7078885-d46b-4cff-8d1f-1c76663cac9d
                  values:
                    - gif
              elementType: craft\elements\Entry
              fieldContext: global
            fieldUid: ff2f85c6-34d2-4894-9228-67896af43011 # gif
            handle: null
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: d0fc824e-f848-45c4-a0b9-7aa2e7bef674
            userCondition: null
            warning: null
            width: 50
        name: Content
        uid: e132ae02-d719-4003-a9ed-90bb2f807198
        userCondition: null
    thumbFieldKey: null
handle: homeimagecard
hasTitleField: true
icon: cards-blank
name: homeImageCard
showSlugField: true
showStatusField: true
slugTranslationKeyFormat: null
slugTranslationMethod: site
titleFormat: null
titleTranslationKeyFormat: null
titleTranslationMethod: site
uiLabelFormat: '{title}'
