allowLineBreaksInTitles: false
color: null
description: null
fieldLayouts:
  3d35bc1e-77e1-402d-b1ed-c2e4a0ee3e22:
    cardThumbAlignment: end
    tabs:
      -
        elementCondition: null
        elements:
          -
            dateAdded: '2026-05-08T10:30:00+00:00'
            editCondition: null
            elementCondition: null
            elementEditCondition: null
            fieldUid: 3c97cebf-a126-4d9a-b681-f07555f654c8 # Initial Background Media
            handle: null
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: 1986c2f0-72b8-4ad1-b918-1fcee72e9505
            userCondition: null
            warning: null
            width: 100
        name: Content
        uid: 3d1812cd-381f-49ad-aaf2-83552aa97e39
        userCondition: null
    thumbFieldKey: null
handle: indexPage
hasTitleField: false
icon: null
name: Index
showSlugField: true
showStatusField: true
slugTranslationKeyFormat: null
slugTranslationMethod: site
titleFormat: Index
titleTranslationKeyFormat: null
titleTranslationMethod: site
uiLabelFormat: '{title}'
