baseUrl: $PRIMARY_SITE_URL
enabled: true
handle: default
hasUrls: true
language: en
name: 'Florian Lechner'
primary: true
siteGroup: 295a13d8-58ef-46ad-ac11-6bd8a6702105 # fl_craftcms_2026
sortOrder: 1
