columnSuffix: null
handle: client
instructions: 'Optional client or publication shown in the project list.'
name: Client
searchable: true
settings:
  byteLimit: null
  charLimit: null
  code: false
  initialRows: 1
  multiline: false
  placeholder: null
  uiMode: normal
translationKeyFormat: null
translationMethod: none
type: craft\fields\PlainText
