columnSuffix: null
handle: description
instructions: 'Intro text shown at the top of the project page.'
name: Description
searchable: true
settings:
  byteLimit: null
  charLimit: null
  code: false
  initialRows: 5
  multiline: true
  placeholder: null
  uiMode: normal
translationKeyFormat: null
translationMethod: none
type: craft\fields\PlainText
