columnSuffix: null
handle: mediaType
instructions: 'Choose either a single image, multiple images at once, a video, or a gif.'
name: 'Media Type'
searchable: false
settings:
  customOptions: false
  options:
    -
      __assoc__:
        -
          - label
          - singleImage
        -
          - value
          - singleImage
        -
          - icon
          - folder-image
        -
          - color
          - '#371a94'
        -
          - default
          - ''
    -
      __assoc__:
        -
          - label
          - multiImage
        -
          - value
          - multiImage
        -
          - icon
          - images
        -
          - color
          - '#0056d6'
        -
          - default
          - ''
    -
      __assoc__:
        -
          - label
          - video
        -
          - value
          - video
        -
          - icon
          - video
        -
          - color
          - '#b92d5d'
        -
          - default
          - ''
    -
      __assoc__:
        -
          - label
          - gif
        -
          - value
          - gif
        -
          - icon
          - file-gif
        -
          - color
          - '#ff6a00'
        -
          - default
          - ''
translationKeyFormat: null
translationMethod: none
type: craft\fields\RadioButtons
