columnSuffix: null
handle: multiImageSpeed
instructions: 'How fast the image should play in milliseconds.'
name: multiImageSpeed
searchable: false
settings:
  byteLimit: null
  charLimit: 7
  code: false
  initialRows: 4
  multiline: false
  placeholder: 'Milliseconds '
  uiMode: normal
translationKeyFormat: null
translationMethod: none
type: craft\fields\PlainText
