columnSuffix: null
handle: selectedWorkCardColumn
instructions: "You are able to control which cards go in the same column.An infinite number of homeImageCard can be added to a column.Your decision how many cards you want to add, but you have to add at least 1 card if you create a column.\r\nThere will be a minimum number of 3 columns and a maximum number of 5 columns on your page."
name: selectedWorkCardColumns
searchable: false
settings:
  createButtonLabel: null
  defaultIndexViewMode: cards
  enableVersioning: false
  entryTypes:
    -
      __assoc__:
        -
          - uid
          - b6211ec8-df28-453c-a214-6967f4ceb00a # homeImageCard
        -
          - group
          - General
  includeTableView: false
  maxEntries: null
  minEntries: 1
  pageSize: 50
  propagationKeyFormat: null
  propagationMethod: all
  showCardsInGrid: false
  viewMode: cards
translationKeyFormat: null
translationMethod: site
type: craft\fields\Matrix
