columnSuffix: null
handle: selectedWorkCardColumnContainerField
instructions: null
name: 'Selected Work Card Column Container Field'
searchable: false
settings:
  createButtonLabel: null
  defaultIndexViewMode: cards
  enableVersioning: false
  entryTypes:
    -
      __assoc__:
        -
          - uid
          - 20afa535-4839-4205-a95e-37726266b742 # Selected Work Card Column
        -
          - group
          - General
  includeTableView: false
  maxEntries: 5
  minEntries: 3
  pageSize: 50
  propagationKeyFormat: null
  propagationMethod: all
  showCardsInGrid: false
  viewMode: cards
translationKeyFormat: null
translationMethod: site
type: craft\fields\Matrix
