defaultPlacement: end
enableVersioning: true
entryTypes:
  -
    uid: 3d7bc8ef-b52a-4233-96fa-a4d276ad46fa # Contact Page Details
handle: contactpage
maxAuthors: 1
name: ContactPage
previewTargets:
  -
    label: 'Primary entry page'
    refresh: '1'
    urlFormat: '{url}'
propagationMethod: all
siteSettings:
  24c4f75f-97a9-4865-98c0-039bb57b8b32: # fl_craftcms_2026
    enabledByDefault: true
    hasUrls: false
    template: null
    uriFormat: null
type: single
