defaultPlacement: end
enableVersioning: true
entryTypes:
  -
    uid: 3c40c666-6a3f-4248-9cde-d3f7895e503c # Homepage
handle: homepage
maxAuthors: 1
name: Homepage
previewTargets:
  -
    label: 'Primary entry page'
    refresh: '1'
    urlFormat: '{url}'
propagationMethod: all
siteSettings:
  24c4f75f-97a9-4865-98c0-039bb57b8b32: # fl_craftcms_2026
    enabledByDefault: true
    hasUrls: true
    template: index.twig
    uriFormat: __home__
type: single
